events {}

http {

    server {
        listen 80;
        server_name localhost;

        return 301 https://localhost:8443$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/nginx-cert.pem;
        ssl_certificate_key /etc/nginx/certs/nginx-key.pem;

        location /api/ {
            proxy_pass http://backend:3000/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}